version: "3"
services:
  bookstore-db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: bookstore
      POSTGRES_USER: bookstore

  bookstore:
    build: .
    image: gcr.io/rails-gcloud-bookstore/bookstore
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: bookstore-db
      DATABASE_USERNAME: bookstore
      DATABASE_PASSWORD: bookstore
    depends_on:
      - bookstore-db

volumes:
  db-data:
